openapi: 3.0.0
info:
  title: aeon pet swagger
  description: aeon pet swagger
  version: 1.0.0
components:
  schemas: {}
paths:
  /:
    get:
      tags:
        - user
        - admin
      description: ヘルスチェック用API
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
